### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by AdityaKalapatapu** [esnet/react-network-diagrams#11]
Error: Cannot find module '/root/workdir/nodejs/node_modules/react-network-diagrams/node_modules/history/npm-scripts/postinstall.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

Installation fails with that error message. On Debian stable/testing. Please advise.

**Comment by jdugan1024** [comment]
What version of node are you using?  What was the exact command line you used to do the install?

**Comment by AdityaKalapatapu** [comment]
Your comment helped me. I was using npm v1.4.21. I have upgraded it to latest v3.8.8 and now I am able to install it. Thanks for the help.

**Comment by jdugan1024** [comment]
Well, that was easy...  :) Glad that helped! Take care.
