### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lukejpreston** [esnet/react-network-diagrams#17]
I would like to use this tool but the documentation lacks. It would be great to be given a vanilla example please

**Comment by pjm17971** [comment]
What are you trying to do?

**Comment by lukejpreston** [comment]
just a simple graph, but there do not seem to be any simple react graphs and this one looks quite nice

**Comment by pjm17971** [comment]
If you want a traffic map, this example is pretty simple. The file has many nodes and edges in it, but the example itself is simple enough:
https://github.com/esnet/react-network-diagrams/blob/master/examples/modules/trafficmap_example.jsx#L173

The format of the topology data is described here:
http://software.es.net/react-network-diagrams/#/trafficmap

You only need the nodes and edges.

(also, if you look at the Editor example and click on the Topo tab, you can see the format. That page lets you build a topology and then cut and paste out the format to use in your application.)

The rest of that document describes the various styling maps. You don't need them to work, but they add styling so you'll want them eventually.

I'll add an item to create a simpler example, though.

**Comment by lukejpreston** [comment]
Just a super simple example would be great, but yeah I didn't look at it properly before so this is useful thanks

**Comment by pjm17971** [comment]
Here's a simpler example, from scratch:
https://github.com/esnet/simple-network-diagram

You can run it here:
http://software.es.net/simple-network-diagram/

Good luck!
