### ISSUE TITLE
import component fails

### ISSUE THREAD

**Issue by benoitblin** [esnet/react-network-diagrams#32]
Thanks for this great module ! Unfortunately, when I try to import any component, I have this error : 
> node_modules/react-network-diagrams/lib/node.js:23
> TypeError: _react2.default.createClass is not a function

My application is running with react 16.4.0

**Comment by sartaj10** [comment]
Hi, this is related to #34 and #35 
Should be fixed soon

**Comment by sartaj10** [comment]
Fixed. `v0.7.0` released
