### ISSUE TITLE
Module not found: Can't resolve 'react-network-diagrams'

### ISSUE THREAD

**Issue by sartaj10** [esnet/react-network-diagrams#35]
Upon creating a new project using create-react-app and adding the diagrams code from the master branch to `package.json`, get the following error 
```
./src/App.js
Module not found: Can't resolve 'react-network-diagrams' in '/Users/ssbaveja/Desktop/Projects/test-diagrams/src'
```

Package.json looks like - 
```
"dependencies": {
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "react-scripts": "1.1.4",
    "react-network-diagrams": "git+https://github.com/esnet/react-network-diagrams.git#master"
  }
```

**Comment by chenkunlia** [comment]
maybe your config is wrong,you can change the dependecies like this:
"dependencies": {
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "react-scripts": "1.1.4",
    "react-network-diagrams": "0.8.0"
  }
